services:

  mysql:
    image: mysql:8.0
    container_name: mysql_apiusuarios
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: coti
      MYSQL_DATABASE: bd_apiusuarios
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: